Part3-team20/Taskify

src/components/SideBar/SideBar.module.scss, src/components/SideBar/SideBarListItem/SideBarListItem.module.scss, src/components/SideBar/SideBarListItem/index.tsx, src/components/SideBar/index.tsx, src/components/button/PaginationButton/PaginationButton.module.scss, src/components/button/PaginationButton/index.tsx
#10 
- 사이드바 컴포넌트 생성했습니다.
- 페이지네이션은 실제 데이터 받아오고 나서 수정할게요!
=> feat: 사이드바 컴포넌트 추가(#10)

src/app/page.tsx, src/components/common/FileInput/FileInput.module.scss, src/components/common/FileInput/index.tsx
#14
- 이미지 파일을 받아오는 fileInput 컴포넌트
- 이미지 미리보기 가능.
- set 함수를 prop 로 받아 컴포넌트 외부로 변경된 이미지 파일을 state 를 통해 받아오도록 했습니다.
=> feature: file-input 컴포넌트

src/app/login/page.tsx, src/app/signup/page.tsx
> #56 
> 로컬 스토리지에 토큰 저장. 
로그인 시 리다이렉트
get 요청 성공 스크린샷
=> localstorage 토큰 저장 및 로그인 시 리다이렉트

src/app/layout.tsx, src/app/login/page.tsx, src/components/MyDashboardList/index.tsx, src/components/modal/ModalPortal.tsx
- #52 
> 모달을 Portal로 관리하도록 했습니다
> 기존의 Modal.tsx 파일은 모달 껍데기로 사용하고, 따로 ModalPortal.tsx 파일 추가했습니다
> 모달을 사용하는 곳에서 ModalPortal 로 감싸서 사용하시면 됩니다
> 제가 아는 선에서 Portal 구현했는데, 이상한 부분 있으면 말해주세요!
=> feature: ModalPortal 적용(#52)

src/components/MyDashboardList/index.tsx, src/components/SideBar/index.tsx, src/components/modal/CreateDashboard/CreateDashboard.module.scss, src/components/modal/CreateDashboard/index.tsx, src/components/modal/ModalPortal.tsx
#32 #10 
- 대시보드 리스트 관련 로직을 실제 데이터 `request`로 변경
- 대시보드 생성 모달 디자인 수정 완료
- 사이드바 모달 수정 
- 브랜치를 잘못 만들어서 이전 PR이랑 커밋이 겹치네요 🥲
=> feature: dashboard list 데이터 연결(#32, #10)

src/app/(home)/page.module.scss
- #79 
> font-size 및 line-height 변경
=> fix: 랜딩페이지 스타일 수정

src/app/(dashboard)/layout.tsx, src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx, src/contexts/dashboardContext.tsx, src/styles/globals.scss
- Dashboard 컨텍스트에서 해당 페이지의 boardId를 추가했습니다.
- 폰트 설정이 적용 안되는 태그가 있어 `*` 추가했습니다.
=> feature: usedashboard-boardId 추가, 폰트 설정 추가 

src/components/Modal/CreateColumn/index.tsx, src/components/Modal/CreateDashboard/index.tsx, src/styles/_reset.scss, src/styles/globals.scss
- 대시보드 추가 성공/실패 토스트 추가
- 이미지 드래그 방지용 스타일 코드 추가
- 컬럼 생성 모달 내부 취소버튼 추가
=> feature: mydashboard toast 추가

src/app/(dashboard)/dashboard/[boardId]/page.tsx, src/app/(dashboard)/mypage/page.tsx, src/components/Modal/CreateTask/index.tsx
=> fix: dashboardId Number 로 수정

src/app/(dashboard)/mypage/page.tsx, src/components/Modal/CreateTask/CreateTask.module.scss, src/components/Modal/ModalInput/DeadlineInput/DeadlineInput.module.scss, src/components/Modal/ModifyTask/ModifyTask.module.scss, src/components/Modal/ModifyTask/index.tsx, src/components/Modal/Task/index.tsx, src/components/common/FileInput/index.tsx
- 모달에서 이미지 첨부 안되는 오류 수정
- 모달 스크롤되게 수정
=> fix: 모달 이미지 첨부 및 스크롤 변경

src/app/(dashboard)/dashboard/[boardId]/page.tsx, src/components/Column/index.tsx, src/components/Modal/CreateTask/index.tsx, src/components/Modal/ModalInput/AssigneeInput/index.tsx, src/components/Modal/ModalInput/DeadlineInput/index.tsx, src/components/Modal/ModalInput/StateInput/index.tsx, src/components/Modal/ModalInput/TagInput/index.tsx, src/components/Modal/ModalPortal.tsx, src/components/Modal/ModifyTask/index.tsx, src/components/common/FileInput/index.tsx, src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
=> fix: import 에러 수정

src/app/(dashboard)/mypage/MyPage.module.scss, src/app/(dashboard)/mypage/page.tsx, src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx, src/components/common/Input/Input.module.scss, src/components/common/Input/index.tsx
- 개별대시보드 헤더에서 프로필 안나오던 것 수정
- 마이페이지 디자인 수정
=> fix: 개별대시보드 헤더 프로필 수정, 마이페이지 input 디자인 수정

src/app/(dashboard)/layout.tsx, src/components/Modal/CreateTask/index.tsx, src/components/Modal/ModalButton/Button/ModalButton.module.scss, src/components/Modal/ModalButton/Button/index.tsx, src/components/Modal/ModalButton/SubmitButton/index.tsx, src/components/Modal/ModifyTask/index.tsx, src/components/common/Button/BasicSubmitButton/index.tsx, src/components/common/Button/Button/Button.module.scss, src/components/common/Header/DashBoardHeader/index.tsx
- 마이페이지에서 개별 대시보드 헤더가 노출되던 문제 수정
- 마이페이지일 경우 헤더 타이틀이 '계정관리'로 노출되도록 수정
=> fix: mypage header

src/components/Card/Card.tsx, src/components/Column/index.tsx, src/components/Modal/CreateTask/CreateTask.module.scss, src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss, src/components/Modal/ModalInput/AssigneeInput/index.tsx, src/components/Modal/ModalInput/StateInput/StateInput.module.scss, src/components/Modal/ModalInput/StateInput/index.tsx, src/components/Modal/ModifyTask/ModifyTask.module.scss, src/components/Modal/ModifyTask/index.tsx, src/components/Modal/Task/Kebob/KebobMenu.tsx, src/components/Modal/Task/index.tsx
=> feat: 수정 모달 연결

src/app/(dashboard)/mypage/page.tsx, src/app/(home)/signup/page.tsx
=> fix: 빌드 오류 수정

src/components/Modal/CreateTask/CreateTask.module.scss, src/components/Modal/ModalInput/DeadlineInput/DeadlineInput.module.scss, src/components/Modal/ModifyTask/ModifyTask.module.scss, src/components/Modal/ModifyTask/index.tsx
- 수정 모달의 버튼의 텍스트 수정
- 모달 우측 padding 값 16px 만큼 조절
=> fix: 모달 디자인 수정

src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/InviteStatus.module.scss, src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/MemberManagement.module.scss, src/components/Modal/ModalInvite/index.tsx
> #30 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
=> 수정 페이지 초대모달버튼, fontsize변경

src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss, src/components/Modal/ModalInput/StateInput/StateInput.module.scss
- div 가로길이가 너무 커서 외부 클릭 시 드롭다운이 안닫히는 문제 수정
=> fix: 담당자모달 / 상태 input 디자인 수정

src/components/Modal/Task/Task.module.scss, src/components/Modal/Task/index.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
=> fix: 모바일 이미지 없을 경우 수정

src/components/Modal/ModalInvite/ModalInvite.module.scss
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
=> style : 초대모달버튼 스타일 조정

src/components/Modal/CreateTask/CreateTask.module.scss, src/components/Modal/ModifyTask/ModifyTask.module.scss
- 일부 기기에서 세로길이가 너무 길어지면 모달도 같이 길어져서, 이 부분 수정했습니다.
- 제가 내일 아침에 나갈 일이 있어서, 승인나면 다른 분이 머지 해주셨으면 합니다! 감사합니다!
=> fix: 할일 생성/수정 모달 세로 수정
